services:
  mysql:
    image: mysql:8.0
    container_name: ipl_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ipl_db
      MYSQL_USER: ipl_user
      MYSQL_PASSWORD: ipl_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend_ipl
      dockerfile: Dockerfile
    container_name: ipl_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ipl_db
      DB_USERNAME: root
      DB_PASSWORD: root
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
