services:
  - type: web
    name: ipl-backend
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ipl-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 10000
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
      - key: DB_HOST
        fromDatabase:
          name: ipl-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ipl-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ipl-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ipl-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ipl-db
          property: password

databases:
  - name: ipl-db
    plan: free
    databaseEngine: mysql
    databaseEngineVersion: 8
